[Interface]
PrivateKey = +IClsRVa+Z6zX/wYxfEWxrsFqwMOqZelzjaCuBsVq3E=
Address = 192.168.4.12/32
DNS = 192.168.4.1

[Peer]
PublicKey = qRIRzvFz4kcJ0U1lzTyIuWlBnAXxC0ITOCU1qoeGcGY=
AllowedIPs = 0.0.0.0/0
Endpoint = wg-vpn.it-xray.ch:51825
